import Head from 'next/head'
import styles from '../styles/Home.module.css'

//import components
import  Hero from '../components/Hero'
import  Navbar from '../components/Navbar'
import  Trending from '../components/Trending'
import  Menu from '../components/Menu'
import  Reviews from '../components/Reviews'
import  Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.background}>
      <Head>
        <title>CafeMugs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto px-20">
        <div>
          <div className="sticky top-0">
            <Navbar/>
          </div>
          <div>
            <Hero />
          </div>
          <div>
            <Trending />
          </div>
          <div>
            <Menu />
          </div>
          <div>
            <Reviews />
          </div>
          <div>
            <Footer />
          </div>
        </div>
      </div>
    </div>
  )
}
